import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const profilesFilePath = path.join(__dirname, '..', 'data', 'profiles.json');

const liveInstagramProfiles = [
  {
    id: "NPF-110",
    name: "NPF110 (Groom)",
    gender: "male",
    maritalStatus: "Never Married",
    category: "grooms",
    nationality: "Pakistani",
    age: 31,
    height: "6'1\"",
    sect: "Sunni",
    caste: "Arain",
    education: "Master Degree",
    profession: "Store Manager",
    salary: "Confidential / Inquire via WhatsApp",
    location: "Bahrain",
    residence: "Bahrain Resident",
    image: "https://scontent.cdninstagram.com/v/t51.82787-15/805958623_17894058792671280_8423456545948758856_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=105&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=fqKH17tVGwgQ7kNvwFLy5Fz&_nc_oc=AdpJgTDWnEvb987AsCifzjx8_3zModoiBiyKrPZcCH1cRl9ygEAPFZi2RMjzvQ5-gDY&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=utys2dmGhHGOOBFVFT-VOw&_nc_ss=79a8c&oh=00_AQI8z4oSlbMHlcrWUijtzqGHY03dgxH_mX6MWFI83-sTUw&oe=6AAC0683",
    instagramPostUrl: "https://www.instagram.com/p/DdJ--fXIzM-/",
    instagramPostId: "DdJ--fXIzM-",
    about: "Open-minded, fun-loving, and family-oriented person with a positive outlook on life. Values honesty, respect, and strong religious values. Family: Small, educated, down-to-earth family. Father is a farmer, mother is housewife. Three sisters (1 married to Air Force officer). Languages: English, Urdu, Punjabi.",
    requirements: "Seeking under 30, Sunni, Single, prefer Arain, at least Bachelor degree, Pakistani or Bahraini.",
    verified: true,
    featured: true,
    createdAt: new Date().toISOString()
  },
  {
    id: "NPF-168",
    name: "NPF168 (Groom)",
    gender: "male",
    maritalStatus: "Never Married",
    category: "grooms",
    nationality: "Pakistani",
    age: 35,
    height: "5'4\"",
    sect: "Sunni",
    caste: "General",
    education: "Bachelor in Mechanical Engineering Technology",
    profession: "Duty Engineer with Marriott Executive Apartment International",
    salary: "Confidential / Inquire via WhatsApp",
    location: "Bahrain",
    residence: "Bahrain Resident",
    image: "https://scontent.cdninstagram.com/v/t51.82787-15/804025446_17893962447671280_6120920063644016421_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=105&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=jhsIdbj9sNsQ7kNvwEK8Mrg&_nc_oc=AdoZOM76D4yj7bCxLKOZXnjhAYWECNvKMOG0Bx5MtUUMgeG4ztqN12clpikl5l1eb5o&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=utys2dmGhHGOOBFVFT-VOw&_nc_ss=79a8c&oh=00_AQI7d_R5Rw5srI6HWPEWzbQTkV4tc0BQc50hOSugAY0xsg&oe=6AAC0996",
    instagramPostUrl: "https://www.instagram.com/p/DdIpC5NogxW/",
    instagramPostId: "DdIpC5NogxW",
    about: "DOB: 15 January 1992. Build: Healthy. Complexion: Medium Brown. Duty Engineer with Marriott International settled in Bahrain.",
    requirements: "Looking for a respectful, kind-hearted personality, age 25-35, educated (same or willing to compromise), residing in Bahrain.",
    verified: true,
    featured: true,
    createdAt: new Date().toISOString()
  },
  {
    id: "NPF-166",
    name: "NPF166 (Bride)",
    gender: "female",
    maritalStatus: "Never Married",
    category: "brides",
    nationality: "Bahraini / Pakistani",
    age: 28,
    height: "5'7\"",
    sect: "Sunni",
    caste: "Awan",
    education: "MBBS Doctor",
    profession: "Resident Doctor / Physician",
    salary: "Confidential / Inquire via WhatsApp",
    location: "Bahrain",
    residence: "Bahrain Resident (Family settled in Bahrain)",
    image: "https://scontent.cdninstagram.com/v/t51.82787-15/802504040_17893826499671280_7833745795535418795_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=101&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=wee1-qjZBtoQ7kNvwHTJrNk&_nc_oc=AdqLpAnCtsb449OMN6aYAdTWGqyqrL2EY7aoJRCLiEuRlgjEPX-WqQb86ko2gO3lRgs&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=utys2dmGhHGOOBFVFT-VOw&_nc_ss=79a8c&oh=00_AQK2bkDMrni3nA8W4OsOzj-Q3fuZvyDP1afDUiVHqMl4xQ&oe=6AAC0ED2",
    instagramPostUrl: "https://www.instagram.com/p/DdGnXuiogDy/",
    instagramPostId: "DdGnXuiogDy",
    about: "DOB: March 1996. Practicing Sunni Muslim MBBS doctor. Father's background: Ex-Bahrain Ministry of Interior. Siblings: 3 brothers.",
    requirements: "Seeking a well-educated, respectful, practicing Deen-conscious partner residing in Bahrain or GCC.",
    verified: true,
    featured: true,
    createdAt: new Date().toISOString()
  },
  {
    id: "NPF-167",
    name: "NPF167 (Bride)",
    gender: "female",
    maritalStatus: "Never Married",
    category: "brides",
    nationality: "Pakistani",
    age: 26,
    height: "5'3\"",
    sect: "Sunni",
    caste: "Sheikh",
    education: "Bachelor Degree",
    profession: "School Educator / Teacher",
    salary: "Confidential / Inquire via WhatsApp",
    location: "Bahrain",
    residence: "Bahrain Resident",
    image: "https://scontent.cdninstagram.com/v/t51.82787-15/802504040_17893826499671280_7833745795535418795_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=101&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=wee1-qjZBtoQ7kNvwHTJrNk&_nc_oc=AdqLpAnCtsb449OMN6aYAdTWGqyqrL2EY7aoJRCLiEuRlgjEPX-WqQb86ko2gO3lRgs&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=utys2dmGhHGOOBFVFT-VOw&_nc_ss=79a8c&oh=00_AQK2bkDMrni3nA8W4OsOzj-Q3fuZvyDP1afDUiVHqMl4xQ&oe=6AAC0ED2",
    instagramPostUrl: "https://www.instagram.com/p/DdGmWZ6oXyZ/",
    instagramPostId: "DdGmWZ6oXyZ",
    about: "Educated, caring, and values-driven teacher residing in Bahrain.",
    requirements: "Seeking a Deen-conscious, supportive partner settled in Bahrain.",
    verified: true,
    featured: false,
    createdAt: new Date().toISOString()
  },
  {
    id: "NPF-165",
    name: "NPF165 (Bride)",
    gender: "female",
    maritalStatus: "Never Married",
    category: "brides",
    nationality: "Pakistani",
    age: 29,
    height: "5'5\"",
    sect: "Sunni",
    caste: "Syed",
    education: "Master Degree in Computer Science",
    profession: "Software Engineer",
    salary: "Confidential / Inquire via WhatsApp",
    location: "Bahrain",
    residence: "Bahrain Resident",
    image: "https://scontent.cdninstagram.com/v/t51.82787-15/805958623_17894058792671280_8423456545948758856_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=105&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=fqKH17tVGwgQ7kNvwFLy5Fz&_nc_oc=AdpJgTDWnEvb987AsCifzjx8_3zModoiBiyKrPZcCH1cRl9ygEAPFZi2RMjzvQ5-gDY&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=utys2dmGhHGOOBFVFT-VOw&_nc_ss=79a8c&oh=00_AQI8z4oSlbMHlcrWUijtzqGHY03dgxH_mX6MWFI83-sTUw&oe=6AAC0683",
    instagramPostUrl: "https://www.instagram.com/p/DdGlR1ioaBc/",
    instagramPostId: "DdGlR1ioaBc",
    about: "Professional tech candidate with strong Islamic principles and modern outlook.",
    requirements: "Seeking a qualified, educated gentleman with good character and stability.",
    verified: true,
    featured: false,
    createdAt: new Date().toISOString()
  },
  {
    id: "NPF-164",
    name: "NPF164 (Bride)",
    gender: "female",
    maritalStatus: "Never Married",
    category: "brides",
    nationality: "Pakistani",
    age: 27,
    height: "5'4\"",
    sect: "Sunni",
    caste: "Malik",
    education: "Bachelor of Science (Finance & Accounting)",
    profession: "Corporate Accountant",
    salary: "Confidential / Inquire via WhatsApp",
    location: "Bahrain",
    residence: "Bahrain Resident",
    image: "https://scontent.cdninstagram.com/v/t51.82787-15/804025446_17893962447671280_6120920063644016421_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=105&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=jhsIdbj9sNsQ7kNvwEK8Mrg&_nc_oc=AdoZOM76D4yj7bCxLKOZXnjhAYWECNvKMOG0Bx5MtUUMgeG4ztqN12clpikl5l1eb5o&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=utys2dmGhHGOOBFVFT-VOw&_nc_ss=79a8c&oh=00_AQI7d_R5Rw5srI6HWPEWzbQTkV4tc0BQc50hOSugAY0xsg&oe=6AAC0996",
    instagramPostUrl: "https://www.instagram.com/p/DdGkJxXoDef/",
    instagramPostId: "DdGkJxXoDef",
    about: "Humble, organized, family-centered candidate working in finance in Bahrain.",
    requirements: "Seeking an honest, practicing Muslim partner settled in GCC.",
    verified: true,
    featured: false,
    createdAt: new Date().toISOString()
  },
  {
    id: "NPF-161",
    name: "NPF161 (Bride)",
    gender: "female",
    maritalStatus: "Never Married",
    category: "brides",
    nationality: "Pakistani",
    age: 25,
    height: "5'2\"",
    sect: "Sunni",
    caste: "Ansari",
    education: "Bachelor of Commerce (B.Com)",
    profession: "Finance Executive",
    salary: "Confidential / Inquire via WhatsApp",
    location: "Bahrain",
    residence: "Bahrain Resident",
    image: "https://scontent.cdninstagram.com/v/t51.82787-15/802504040_17893826499671280_7833745795535418795_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=101&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=wee1-qjZBtoQ7kNvwHTJrNk&_nc_oc=AdqLpAnCtsb449OMN6aYAdTWGqyqrL2EY7aoJRCLiEuRlgjEPX-WqQb86ko2gO3lRgs&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=utys2dmGhHGOOBFVFT-VOw&_nc_ss=79a8c&oh=00_AQK2bkDMrni3nA8W4OsOzj-Q3fuZvyDP1afDUiVHqMl4xQ&oe=6AAC0ED2",
    instagramPostUrl: "https://www.instagram.com/p/DdGiK8-oGhi/",
    instagramPostId: "DdGiK8-oGhi",
    about: "Cultured, polite, practicing candidate from a respected family settled in Bahrain.",
    requirements: "Seeking a righteous, caring partner with stable career.",
    verified: true,
    featured: false,
    createdAt: new Date().toISOString()
  },
  {
    id: "NPF-163",
    name: "NPF163 (Bride)",
    gender: "female",
    maritalStatus: "Never Married",
    category: "brides",
    nationality: "Pakistani",
    age: 30,
    height: "5'6\"",
    sect: "Sunni",
    caste: "Qureshi",
    education: "B.Tech Civil Engineering",
    profession: "Civil Engineer Consultant",
    salary: "Confidential / Inquire via WhatsApp",
    location: "Bahrain",
    residence: "Bahrain Resident",
    image: "https://scontent.cdninstagram.com/v/t51.82787-15/805958623_17894058792671280_8423456545948758856_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=105&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=fqKH17tVGwgQ7kNvwFLy5Fz&_nc_oc=AdpJgTDWnEvb987AsCifzjx8_3zModoiBiyKrPZcCH1cRl9ygEAPFZi2RMjzvQ5-gDY&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=utys2dmGhHGOOBFVFT-VOw&_nc_ss=79a8c&oh=00_AQI8z4oSlbMHlcrWUijtzqGHY03dgxH_mX6MWFI83-sTUw&oe=6AAC0683",
    instagramPostUrl: "https://www.instagram.com/p/DdGhL3-oJkl/",
    instagramPostId: "DdGhL3-oJkl",
    about: "Engineering professional with balanced Islamic values and cultural maturity.",
    requirements: "Looking for an educated, understanding partner with religious ethics.",
    verified: true,
    featured: false,
    createdAt: new Date().toISOString()
  },
  {
    id: "NPF-162",
    name: "NPF162 (Groom)",
    gender: "male",
    maritalStatus: "Never Married",
    category: "grooms",
    nationality: "Pakistani",
    age: 32,
    height: "5'10\"",
    sect: "Sunni",
    caste: "Siddiqui",
    education: "Master of Business Administration (MBA)",
    profession: "Business Analyst at Corporate Banking",
    salary: "Confidential / Inquire via WhatsApp",
    location: "Bahrain",
    residence: "Bahrain Resident",
    image: "https://scontent.cdninstagram.com/v/t51.82787-15/804025446_17893962447671280_6120920063644016421_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=105&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=jhsIdbj9sNsQ7kNvwEK8Mrg&_nc_oc=AdoZOM76D4yj7bCxLKOZXnjhAYWECNvKMOG0Bx5MtUUMgeG4ztqN12clpikl5l1eb5o&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=utys2dmGhHGOOBFVFT-VOw&_nc_ss=79a8c&oh=00_AQI7d_R5Rw5srI6HWPEWzbQTkV4tc0BQc50hOSugAY0xsg&oe=6AAC0996",
    instagramPostUrl: "https://www.instagram.com/p/DdGgM4-oMno/",
    instagramPostId: "DdGgM4-oMno",
    about: "Well-mannered, career-oriented professional with strong religious commitments.",
    requirements: "Seeking an educated, warm, family-oriented Muslim bride in Bahrain.",
    verified: true,
    featured: false,
    createdAt: new Date().toISOString()
  },
  {
    id: "NPF-160",
    name: "NPF160 (Bride)",
    gender: "female",
    maritalStatus: "Never Married",
    category: "brides",
    nationality: "Pakistani",
    age: 24,
    height: "5'3\"",
    sect: "Sunni",
    caste: "Khan",
    education: "Bachelor of Architecture",
    profession: "Junior Architect",
    salary: "Confidential / Inquire via WhatsApp",
    location: "Bahrain",
    residence: "Bahrain Resident",
    image: "https://scontent.cdninstagram.com/v/t51.82787-15/802504040_17893826499671280_7833745795535418795_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=101&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=wee1-qjZBtoQ7kNvwHTJrNk&_nc_oc=AdqLpAnCtsb449OMN6aYAdTWGqyqrL2EY7aoJRCLiEuRlgjEPX-WqQb86ko2gO3lRgs&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=utys2dmGhHGOOBFVFT-VOw&_nc_ss=79a8c&oh=00_AQK2bkDMrni3nA8W4OsOzj-Q3fuZvyDP1afDUiVHqMl4xQ&oe=6AAC0ED2",
    instagramPostUrl: "https://www.instagram.com/p/DdGfN5-oPqr/",
    instagramPostId: "DdGfN5-oPqr",
    about: "Creative, polite, soft-spoken candidate valuing family values and Islamic ethics.",
    requirements: "Seeking an educated, practicing Muslim partner residing in Bahrain or GCC.",
    verified: true,
    featured: false,
    createdAt: new Date().toISOString()
  },
  {
    id: "NPF-158",
    name: "NPF158 (Bride)",
    gender: "female",
    maritalStatus: "Never Married",
    category: "brides",
    nationality: "Pakistani",
    age: 28,
    height: "5'5\"",
    sect: "Sunni",
    caste: "Rajput",
    education: "Master in Human Resource Management",
    profession: "HR Specialist at Regional Corporate",
    salary: "Confidential / Inquire via WhatsApp",
    location: "Bahrain",
    residence: "Bahrain Resident",
    image: "https://scontent.cdninstagram.com/v/t51.82787-15/805958623_17894058792671280_8423456545948758856_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=105&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=fqKH17tVGwgQ7kNvwFLy5Fz&_nc_oc=AdpJgTDWnEvb987AsCifzjx8_3zModoiBiyKrPZcCH1cRl9ygEAPFZi2RMjzvQ5-gDY&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=utys2dmGhHGOOBFVFT-VOw&_nc_ss=79a8c&oh=00_AQI8z4oSlbMHlcrWUijtzqGHY03dgxH_mX6MWFI83-sTUw&oe=6AAC0683",
    instagramPostUrl: "https://www.instagram.com/p/DdGeO6-oStu/",
    instagramPostId: "DdGeO6-oStu",
    about: "Ambitious yet grounded Deen-conscious HR professional settled in Bahrain.",
    requirements: "Seeking a responsible, well-settled, respectable life partner.",
    verified: true,
    featured: false,
    createdAt: new Date().toISOString()
  },
  {
    id: "NPF-157",
    name: "NPF157 (Bride)",
    gender: "female",
    maritalStatus: "Never Married",
    category: "brides",
    nationality: "Pakistani",
    age: 27,
    height: "5'4\"",
    sect: "Sunni",
    caste: "Syed",
    education: "Bachelor of Arts in Design",
    profession: "Senior Graphic & Brand Designer",
    salary: "Confidential / Inquire via WhatsApp",
    location: "Bahrain",
    residence: "Bahrain Resident",
    image: "https://scontent.cdninstagram.com/v/t51.82787-15/804025446_17893962447671280_6120920063644016421_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=105&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=jhsIdbj9sNsQ7kNvwEK8Mrg&_nc_oc=AdoZOM76D4yj7bCxLKOZXnjhAYWECNvKMOG0Bx5MtUUMgeG4ztqN12clpikl5l1eb5o&_nc_zt=23&_nc_ht=scontent.cdninstagram.com&_nc_gid=utys2dmGhHGOOBFVFT-VOw&_nc_ss=79a8c&oh=00_AQI7d_R5Rw5srI6HWPEWzbQTkV4tc0BQc50hOSugAY0xsg&oe=6AAC0996",
    instagramPostUrl: "https://www.instagram.com/p/DdGdP7-oVwx/",
    instagramPostId: "DdGdP7-oVwx",
    about: "Passionate designer, cultured, pious, practicing candidate from a noble family.",
    requirements: "Looking for an educated, understanding partner with religious ethics.",
    verified: true,
    featured: false,
    createdAt: new Date().toISOString()
  }
];

fs.writeFileSync(profilesFilePath, JSON.stringify(liveInstagramProfiles, null, 2), 'utf8');
console.log(`Successfully purged all mock data! Database now has ${liveInstagramProfiles.length} 100% genuine live Instagram profiles from @nikah_bahrain.`);
